version: "3.9"

###########################################################################
# Named volumes (persistent even after `docker compose down`)
###########################################################################
volumes:
  mysqldata: # MySQL data
  backend_vendor: # PHP vendor directory
  frontend_node_modules: # Node.js modules

###########################################################################
# Networks
###########################################################################
networks:
  twitter_network:
    driver: bridge

services:
  #########################################################################
  # 1. MySQL Database                                                    #
  #########################################################################
  db:
    image: mysql:8.0
    container_name: twitter_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony_db}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - twitter_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MYSQL_USER:-symfony}", "-p${MYSQL_PASSWORD:-symfony}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  #########################################################################
  # 2. Backend Symfony + Apache                                          #
  #########################################################################
  backend:
    build:
      context: ./backend
      target: development
    container_name: twitter_backend
    ports:
      - "8001:80"
    env_file:
      - ./backend/.env.docker
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_DISPLAY_ERRORS: "On"
      PHP_MEMORY_LIMIT: "256M"
    volumes:
      # Development: mount source code for hot reload
      - ./backend:/var/www/html:cached
      # Persist vendor directory
      - backend_vendor:/var/www/html/vendor
    networks:
      - twitter_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  #########################################################################
  # 3. Frontend Vite (React)                                             #
  #########################################################################
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: twitter_frontend
    ports:
      - "5173:5173"
    volumes:
      # Development: mount source code for hot reload
      - ./frontend:/app:cached
      # Persist node_modules
      - frontend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8001
      ROLLUP_NO_NATIVE: "true"
      CHOKIDAR_USEPOLLING: "true"
      # Increase memory limit for Node.js
      NODE_OPTIONS: "--max_old_space_size=4096"
    networks:
      - twitter_network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s